In [1]:
import numpy as np 

In [2]:
ND = np.random.randint(0, 10, (4,4) ) #element-wise
ND 

array([[6, 7, 1, 9],
       [8, 5, 3, 4],
       [3, 5, 3, 6],
       [3, 5, 3, 7]])

In [4]:
ND2 = np.random.randint(0, 10, (4,4) ) #element-wise
ND2 

array([[0, 5, 1, 7],
       [3, 4, 4, 5],
       [7, 8, 7, 0],
       [4, 6, 6, 9]])

In [5]:
ND + ND2

array([[ 6, 12,  2, 16],
       [11,  9,  7,  9],
       [10, 13, 10,  6],
       [ 7, 11,  9, 16]])

In [6]:
ND3 = np.random.randint(0, 10, (2,2) ) #element-wise
ND3

array([[6, 0],
       [3, 8]])

In [7]:
ND4 = np.random.randint(0, 10, (1,3) ) #element-wise
ND4

array([[8, 9, 9]])