In [1]:
import numpy as np 

In [3]:
ND = np.arange(15).reshape(3,5)
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
ND[1,1]

6

In [6]:
ND[2]

array([10, 11, 12, 13, 14])

In [7]:
ND[:, 2]

array([ 2,  7, 12])

In [10]:
ND[0,0] = 99
ND

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
ND[: , 2] = 44

In [12]:
ND

array([[99,  1, 44,  3,  4],
       [ 5,  6, 44,  8,  9],
       [10, 11, 44, 13, 14]])

In [13]:
ND = np.delete(ND, 0, axis=1)
ND

array([[ 1, 44,  3,  4],
       [ 6, 44,  8,  9],
       [11, 44, 13, 14]])

In [14]:
ND = np.delete(ND, 2, axis=0)
ND

array([[ 1, 44,  3,  4],
       [ 6, 44,  8,  9]])

In [15]:
ND

array([[ 1, 44,  3,  4],
       [ 6, 44,  8,  9]])

In [17]:
ND = np.append(ND, [[7,7,7,7]], axis=0)
ND

array([[ 1, 44,  3,  4],
       [ 6, 44,  8,  9],
       [ 7,  7,  7,  7]])

In [19]:
ND = np.insert(ND, 0, [[6,6,6,6]], axis=0)
ND

array([[ 6,  6,  6,  6],
       [ 6,  6,  6,  6],
       [ 1, 44,  3,  4],
       [ 6, 44,  8,  9],
       [ 7,  7,  7,  7]])

In [23]:
ND = np.append(ND, [ [33], [33], [33], [33], [33]], axis=1)
ND

array([[ 6,  6,  6,  6, 33, 33],
       [ 6,  6,  6,  6, 33, 33],
       [ 1, 44,  3,  4, 33, 33],
       [ 6, 44,  8,  9, 33, 33],
       [ 7,  7,  7,  7, 33, 33]])

In [34]:
ND = np.arange(20).reshape(4,5)
ND  

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
ND = np.insert(ND, 1, [[21,22,23,24,25]], axis=0)
ND

array([[ 0,  1,  2,  3,  4],
       [21, 22, 23, 24, 25],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
ND = np.insert(ND, 2, [31,31,31,31], axis=1)

In [36]:
ND

array([[ 0,  1, 31,  2,  3,  4],
       [ 5,  6, 31,  7,  8,  9],
       [10, 11, 31, 12, 13, 14],
       [15, 16, 31, 17, 18, 19]])