In [1]:
import numpy as np

In [2]:
ND = np.array([1,2,3,4,5])
ND

array([1, 2, 3, 4, 5])

In [3]:
PL = [1,2,3,4,5]
PL

[1, 2, 3, 4, 5]

In [4]:
ND = np.array([[1,2,3,4,5], [1,2,3,4,5] ])
ND

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [11]:
print("shape : " , ND.shape)
print("size : " , ND.size)
print("dimension : ", ND.ndim)

shape :  (2, 5)
size :  10
dimension :  2


In [10]:
ND.dtype #elemanlarının veri tipi 
# tüm elemanları aynı veri tipinde olması gerekiyor...

dtype('int64')

In [13]:
ND3 = np.array([[[1,2,3,4,5], [1,2,3,4,5] ] , [ [1,2,3,4,5], [1,2,3,4,5] ] ])
ND3

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [14]:
ND3.ndim

3

In [15]:
ND3.shape

(2, 2, 5)

In [16]:
#  0 boyutlu ndarray
ND0 = np.array(4)
ND0

array(4)

In [17]:
ND0.ndim

0

In [18]:
NDX = np.array([4])
NDX

array([4])

In [19]:
NDX.ndim

1