In [1]:
import numpy as np 

In [2]:
ND = np.arange(20).reshape(4,5)
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
ND[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
ND[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
ND[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
ND[:2, :2]

array([[0, 1],
       [5, 6]])

In [10]:
SLICED_ND = ND[1:4, 2:4]
SLICED_ND

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [11]:
SLICED_ND[0,0] = 99
SLICED_ND

array([[99,  8],
       [12, 13],
       [17, 18]])

In [12]:
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 99,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
ND = np.arange(12).reshape(3,4)
ND 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
SLICED_ND = ND[:2, :2]
SLICED_ND

array([[0, 1],
       [4, 5]])

In [16]:
SLICED_ND[0,0] = 100
SLICED_ND

array([[100,   1],
       [  4,   5]])

In [17]:
ND

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [18]:
SLICED_2 = ND[:2, :2].copy()
SLICED_2 

array([[100,   1],
       [  4,   5]])

In [19]:
ND = np.random.randint(0, 10, (4,5))
ND

array([[4, 1, 8, 4, 4],
       [0, 2, 7, 8, 1],
       [8, 9, 3, 9, 9],
       [1, 0, 3, 0, 3]])

In [20]:
ND[:] >= 5

array([[False, False,  True, False, False],
       [False, False,  True,  True, False],
       [ True,  True, False,  True,  True],
       [False, False, False, False, False]])

In [21]:
ND[ND[:] >= 5]

array([8, 7, 8, 8, 9, 9, 9])

In [25]:
ND[(ND[:] >= 5) & (ND[:] < 9)]

array([8, 7, 8, 8])